### ISSUE TITLE
Can't choose custom resolution

### ISSUE THREAD

**Issue by DonelBueno** [wipeout-phantom-edition/wipeout-phantom-edition#6]
Hey, guys.

The game works great for the most part, but I can't downsample with Nvidia DSR because it always choose my native resolution, even if I change my desktop resolution to a DSR one before launching the game.

Do you guys intend to add support for choosing the full screen resolution from the video modes available instead of always getting the desktop one?

I would like to supersample the game because it looks very aliased at 1920x1080.

**Comment by wipeout-phantom-edition** [comment]
The next release will add exclusive fullscreen mode and will allow you to specify an exclusive fullscreen resolution in `wipeout.cfg`, but by default it will match your desktop resolution.

**Comment by wipeout-phantom-edition** [comment]
Added in [v1.0.77](https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/releases/tag/v1.0.77).

I'm not very familiar with DSR but from what I understand you need to use the exact resolution(s) that show up next to the selected options in the `DSR - Factors` in Nvidia Control Panel. This can be specified in `wipeout.cfg` with the `exclusiveFullscreenResolution` variable. The default 0 option will use the current desktop resolution. The window mode must also be set to "EXCLUSIVE FS" in the graphics options menu.

I tried using DSR but it keeps minimizng the window right after switching to fullscreen. I think this is a specific issue with my machine because other games do this too.

**Comment by DonelBueno** [comment]
It works fine here, thank you very much =)

Try disabling "full screen optimizations" and change the "hi-dpi settings" on the .exe settings:

![image](https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/assets/4239694/e459f38f-e291-4812-aefb-248e5adf1d0c)

It's in portuguese, but I guess you can locate it.
